{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "0bf7fcd1_738a8496",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 11805
      },
      "writtenOn": "2023-01-23T20:12:14Z",
      "side": 1,
      "message": "charm-recheck\n\n2023-01-21 14:23:32.603370 | focal-medium | 2023-01-21 14:23:32 [INFO] Running restart-services on ovn-chassis/0\n2023-01-21 14:23:35.413497 | focal-medium | 2023-01-21 14:23:35 [INFO] Running restart-services on ovn-chassis/1\n2023-01-21 15:08:38.351659 | focal-medium | 2023-01-21 15:08:38 [INFO] ERROR\n2023-01-21 15:08:38.353165 | focal-medium | 2023-01-21 15:08:38 [INFO] \u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\n2023-01-21 15:08:38.353231 | focal-medium | 2023-01-21 15:08:38 [INFO] ERROR: test_deferred_restarts (zaza.openstack.charm_tests.ovn.tests.OVNChassisDeferredRestartTest)\n2023-01-21 15:08:38.353242 | focal-medium | 2023-01-21 15:08:38 [INFO] Run deferred restart tests.\n2023-01-21 15:08:38.353250 | focal-medium | 2023-01-21 15:08:38 [INFO] ----------------------------------------------------------------------\n2023-01-21 15:08:38.353257 | focal-medium | 2023-01-21 15:08:38 [INFO] Traceback (most recent call last):\n2023-01-21 15:08:38.353313 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/test_utils.py\", line 1289, in test_deferred_restarts\n2023-01-21 15:08:38.353328 | focal-medium | 2023-01-21 15:08:38 [INFO]     self.run_tests()\n2023-01-21 15:08:38.353342 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/ovn/tests.py\", line 644, in run_tests\n2023-01-21 15:08:38.353373 | focal-medium | 2023-01-21 15:08:38 [INFO]     self.run_package_change_test(\n2023-01-21 15:08:38.353968 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/test_utils.py\", line 1237, in run_package_change_test\n2023-01-21 15:08:38.353992 | focal-medium | 2023-01-21 15:08:38 [INFO]     self.check_clear_restarts()\n2023-01-21 15:08:38.354000 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/test_utils.py\", line 930, in check_clear_restarts\n2023-01-21 15:08:38.354007 | focal-medium | 2023-01-21 15:08:38 [INFO]     self.check_status_message_is_clear()\n2023-01-21 15:08:38.354014 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/openstack/charm_tests/test_utils.py\", line 908, in check_status_message_is_clear\n2023-01-21 15:08:38.354020 | focal-medium | 2023-01-21 15:08:38 [INFO]     model.block_until_unit_wl_message_match(\n2023-01-21 15:08:38.354027 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py\", line 224, in _wrapper\n2023-01-21 15:08:38.354452 | focal-medium | 2023-01-21 15:08:38 [INFO]     return future.result(timeout)\n2023-01-21 15:08:38.354486 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n2023-01-21 15:08:38.354505 | focal-medium | 2023-01-21 15:08:38 [INFO]     return self.__get_result()\n2023-01-21 15:08:38.354551 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n2023-01-21 15:08:38.354564 | focal-medium | 2023-01-21 15:08:38 [INFO]     raise self._exception\n2023-01-21 15:08:38.354573 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/__init__.py\", line 209, in _runner\n2023-01-21 15:08:38.354580 | focal-medium | 2023-01-21 15:08:38 [INFO]     return await f(*args, **kwargs)\n2023-01-21 15:08:38.354589 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/model.py\", line 2538, in async_block_until_unit_wl_message_match\n2023-01-21 15:08:38.354596 | focal-medium | 2023-01-21 15:08:38 [INFO]     await async_block_until(_unit_status, timeout\u003dtimeout)\n2023-01-21 15:08:38.354992 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/home/ubuntu/src/review.opendev.org/x/charm-ovn-chassis/src/.tox/func-target/lib/python3.8/site-packages/zaza/model.py\", line 1935, in async_block_until\n2023-01-21 15:08:38.355015 | focal-medium | 2023-01-21 15:08:38 [INFO]     await asyncio.wait_for(_block(), timeout)\n2023-01-21 15:08:38.355023 | focal-medium | 2023-01-21 15:08:38 [INFO]   File \"/usr/lib/python3.8/asyncio/tasks.py\", line 501, in wait_for\n2023-01-21 15:08:38.355030 | focal-medium | 2023-01-21 15:08:38 [INFO]     raise exceptions.TimeoutError()\n2023-01-21 15:08:38.355037 | focal-medium | 2023-01-21 15:08:38 [INFO] asyncio.exceptions.TimeoutError",
      "revId": "48e33c2ffb4fb214e3c6daef1d2a100d4adae077",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "269ae9d5_469c0331",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 11805
      },
      "writtenOn": "2023-01-23T21:33:07Z",
      "side": 1,
      "message": "charm-recheck\n\nThe following was merged today. Let\u0027s see if it helps: https://github.com/openstack-charmers/zosci-config/pull/259",
      "revId": "48e33c2ffb4fb214e3c6daef1d2a100d4adae077",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "6a075023_ff766465",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 11805
      },
      "writtenOn": "2023-01-24T15:03:14Z",
      "side": 1,
      "message": "jammy-zed is hitting the same timeout error as the previous run.\n\nThe plan for this change is to hold off on fixing any CI failures and therefore hold off on merging until another contributor needs to backport a patch to this stable branch in the future. At that point the team will revisit this change, fix any blockers, and get them merged in order to unblock the contributor\u0027s change.",
      "revId": "48e33c2ffb4fb214e3c6daef1d2a100d4adae077",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}