{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "dec4be79_902693f9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 24824
      },
      "writtenOn": "2022-08-29T12:52:59Z",
      "side": 1,
      "message": "2022-08-24 12:20:04 DEBUG unit.ovn-chassis/0.install logger.go:60   Installing build dependencies: finished with status \u0027error\u0027\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60   error: subprocess-exited-with-error\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60   \n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60   × pip subprocess to install build dependencies did not run successfully.\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60   │ exit code: 1\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60   ╰─\u003e [3 lines of output]\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60       Looking in links: wheelhouse\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60       ERROR: Could not find a version that satisfies the requirement flit_core\u003c3,\u003e\u003d2 (from versions: 3.7.1)\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60       ERROR: No matching distribution found for flit_core\u003c3,\u003e\u003d2\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60       [end of output]\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60   \n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60   note: This error originates from a subprocess, and is likely not a problem with pip.\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60 error: subprocess-exited-with-error\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60 \n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60 × pip subprocess to install build dependencies did not run successfully.\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60 │ exit code: 1\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60 ╰─\u003e See above for output.\n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60 \n2022-08-24 12:20:04 WARNING unit.ovn-chassis/0.install logger.go:60 note: This error originates from a subprocess, and is likely not a problem with pip.\n2022-08-24 12:20:05 WARNING unit.ovn-chassis/0.install logger.go:60 Traceback (most recent call last):\n2022-08-24 12:20:05 WARNING unit.ovn-chassis/0.install logger.go:60   File \"/var/lib/juju/agents/unit-ovn-chassis-0/charm/hooks/install\", line 8, in \u003cmodule\u003e\n2022-08-24 12:20:05 WARNING unit.ovn-chassis/0.install logger.go:60     basic.bootstrap_charm_deps()\n2022-08-24 12:20:05 WARNING unit.ovn-chassis/0.install logger.go:60   File \"/var/lib/juju/agents/unit-ovn-chassis-0/charm/lib/charms/layer/basic.py\", line 224, in bootstrap_charm_deps\n2022-08-24 12:20:05 WARNING unit.ovn-chassis/0.install logger.go:60     check_call([pip, \u0027install\u0027, \u0027-U\u0027, reinstall_flag, \u0027--no-index\u0027,\n2022-08-24 12:20:05 WARNING unit.ovn-chassis/0.install logger.go:60   File \"/usr/lib/python3.8/subprocess.py\", line 364, in check_call\n2022-08-24 12:20:05 WARNING unit.ovn-chassis/0.install logger.go:60     raise CalledProcessError(retcode, cmd)\n2022-08-24 12:20:05 WARNING unit.ovn-chassis/0.install logger.go:60 subprocess.CalledProcessError: Command \u0027[\u0027/var/lib/juju/agents/unit-ovn-chassis-0/.venv/bin/pip\u0027, \u0027install\u0027, \u0027-U\u0027, \u0027--force-reinstall\u0027, \u0027--no-index\u0027, \u0027--no-cache-dir\u0027, \u0027-f\u0027, \u0027wheelhouse\u0027, \u0027pyrsistent\u003d\u003d0.18.1\u0027, \u0027charms.reactive\u003d\u003d1.5.0\u0027, \u0027charms.openstack\u003d\u003d0.0.1.dev1\u0027, \u0027pkgutil-resolve-name\u003d\u003d1.3.10\u0027, \u0027importlib-resources\u003d\u003d5.9.0\u0027, \u0027pbr\u003d\u003d5.10.0\u0027, \u0027pyparsing\u003d\u003d3.0.9\u0027, \u0027pyaml\u003d\u003d21.10.1\u0027, \u0027dnspython\u003d\u003d1.16.0\u0027, \u0027psutil\u003d\u003d5.9.1\u0027, \u0027jsonschema\u003d\u003d4.14.0\u0027, \u0027netaddr\u003d\u003d0.7.19\u0027, \u0027tomli\u003d\u003d2.0.1\u0027, \u0027packaging\u003d\u003d21.3\u0027, \u0027flit-core\u003d\u003d3.7.1\u0027, \u0027charmhelpers\u003d\u003d1.1.1.dev37\u0027, \u0027zipp\u003d\u003d3.8.1\u0027, \u0027PyYAML\u003d\u003d5.3.1\u0027, \u0027attrs\u003d\u003d22.1.0\u0027, \u0027netifaces\u003d\u003d0.11.0\u0027, \u0027Jinja2\u003d\u003d3.1.2\u0027]\u0027 returned non-zero exit status 1.",
      "revId": "7138cf7560f4af52cbea78af03c85be4b7f9c2a4",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}